apiVersion: apps/v1
kind: Deployment
metadata:
  name: newhello-deployment
  labels:
    app: newhello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newhello
  template:
    metadata:
      labels:
        app: newhello
    spec:
      containers:
      - name: python-container
        image: local-flask-helloworld:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-service
spec:
  type: LoadBalancer
  selector:
    app: newhello
  ports:
    - port: 8000
      targetPort: 8000
